apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: aws-iam-operator-manager
  name: system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: acct
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-iam-operator-manager
  namespace: system
  labels:
    control-plane: aws-iam-operator-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: aws-iam-operator-manager
  template:
    metadata:
      labels:
        control-plane: aws-iam-operator-manager
    spec:
      serviceAccountName: acct
      containers:
      - args:
        - --enable-leader-election
        image: redradrat/aws-iam-operator:v0.2.0
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
